enable-magisk-update = true
parallel-jobs = 1
compression-level = 9

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[X-piko]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
patches-source = "crimera/piko"
included-patches = "'Hide For You' 'Hide Live Threads' 'Disable chirp font' 'Remove view count' 'Hide Banner' 'Hide FAB' 'Hide FAB Menu Buttons' 'Hide Promoted Trends' 'Hide Community Notes' 'Google Ads Patch'"
integrations-source = "crimera/revanced-integrations"
enabled = false

[X-piko-dev]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
patches-source = "crimera/piko"
included-patches = "'Hide For You' 'Hide Live Threads' 'Disable chirp font' 'Remove view count' 'Hide Banner' 'Hide FAB' 'Hide FAB Menu Buttons' 'Hide Promoted Trends' 'Hide Community Notes' 'Google Ads Patch'"
integrations-source = "crimera/revanced-integrations"
patches-version = "dev"
enabled = false

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
included-patches = "'SIM spoof'"

[Reddit-Ex]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
excluded-patches = "'Custom branding name for Reddit'"

[Reddit-Ex-dev]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
excluded-patches = "'Custom branding name for Reddit'"
patches-version = "dev"

[YouTube-Ex]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'MaterialYou' 'Return YouTube Username'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme'"
build-mode = "both"

[YouTube-Ex-Dev]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'MaterialYou' 'Return YouTube Username'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme'"
build-mode = "both"
patches-version = "dev"

[Music-Ex]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Return YouTube Username'"
build-mode = "both"

[Music-Ex-dev]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Return YouTube Username'"
build-mode = "both"
patches-version = "dev"
